version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: peak_ecommerce
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
